name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.4.4
  - pip=22.2.2
  - scikit-learn=1.1.2
  - matplotlib==3.5.3
  - plotly==5.10.0
  - pillow=9.2.0
  - mlflow=1.29.0
  - pip:
      - wandb==0.13.3
      - omegaconf==2.2.3